name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: tap HEAD
        run: brew tap packrat386/tools-testing file://$(pwd)

      - name: install sk
        run: brew install packrat386/tools-testing/sk

      - name: test sk
        run: brew test packrat386/tools-testing/sk
        if: runner.os != 'Linux' # zsh tests don't work on Ubuntu

      - name: install kamino
        run: brew install packrat386/tools-testing/kamino

      - name: test kamino
        run: brew test packrat386/tools-testing/kamino
